### ISSUE TITLE
I want to use this package with latest XUnit from NuGet. 

### ISSUE THREAD

**Issue by SergeyKulgan** [GreanTech/Exude#22] opened 2016-07-04 17:44 UTC
It is good package, I tried, it works with XUnit 1.9.2  but not works with 2.0.0 or 2.1.0.  I want  to control tests output by using Xunit.Abstractions.ITestOutputHelper  from xunit.abstractions dll.  But it seems that type missing in xunit version 1.9.2 dll.

**Comment by moodmosaic** [comment] 2016-07-05 04:37
Upgrading Exude to xUnit.net 2.x [doesn't seem to be trivial](https://github.com/GreanTech/Exude/issues/21) (if doable at all, without a rewrite).

**Comment by ploeh** [comment] 2016-07-05 04:59
Closing this issue as a duplicate of #21.

**Comment by ploeh** [comment] 2016-07-05 04:59
Or, rather, I'd like to close this issue, but I don't have the rights to do that in this repository. @flensted, @sgryt, will one of you consider closing this issue?

**Closed as completed** 2016-07-05 05:31 UTC
